#!/usr/bin/env ruby

require "menthol"

profile = Menthol::Profile.configure(File.expand_path("~/.mentholrc"))

case ARGV.first
when "sync"
  profile.sync_all!

  profile.providers.each do |provider|
    provider.accounts.each do |account|
      puts ["===", account.provider, "|", account.name, "==="].join(" ")
      puts account.amount.format
    end
  end

  puts "=== Total ==="
  puts profile.amount.format
else
  puts "usage: menthold COMMAND"
end

exit 0
